# Generated by Django 4.0.5 on 2022-06-11 13:47

from django.db import migrations, models
import skyeng.internal.models.theme.model


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AddField(
            model_name='theme',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], default=skyeng.internal.models.theme.model.Level['A1'], max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
