# Generated by Django 4.0.5 on 2022-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0002_alter_category_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], max_length=10),
        ),
    ]
