# Generated by Django 4.0.5 on 2022-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0002_user_repeat_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repeat_words',
        ),
        migrations.AddField(
            model_name='user',
            name='word_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
