# Generated by Django 4.0.5 on 2022-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0004_remove_theme_text_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
