# Generated by Django 4.0.5 on 2022-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0006_word_example_word_transcription_word_translation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Upper-Intermediate', 'Upper-Intermediate'), ('Advanced', 'Advanced'), ('Proficiency', 'Proficiency')], max_length=30, null=True),
        ),
    ]
