# Generated by Django 4.0.5 on 2022-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0007_rename_title_category_name_rename_title_theme_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='theme',
        ),
        migrations.AddField(
            model_name='word',
            name='theme',
            field=models.ManyToManyField(to='skyeng.theme'),
        ),
    ]
