# Generated by Django 4.0.5 on 2022-06-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0008_alter_category_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['name'], 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='theme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='skyeng.category'),
        ),
        migrations.AlterField(
            model_name='word',
            name='theme',
            field=models.ManyToManyField(related_name='words', to='skyeng.theme'),
        ),
    ]
