# Generated by Django 4.0.5 on 2022-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0010_alter_category_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sound',
            field=models.FileField(blank=True, upload_to='musics/'),
        ),
    ]
