# Generated by Django 4.0.5 on 2022-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0012_alter_word_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='theme',
        ),
        migrations.AddField(
            model_name='word',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='words', to='skyeng.theme'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.FileField(null=True, upload_to='sounds/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
