# Generated by Django 4.0.5 on 2022-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyeng', '0013_remove_word_theme_word_themes_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=30, null=True),
        ),
    ]
