version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver
    ports:
      - "8000:8000"
  db:
    image: postgres:12.11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hello_django_dev
  volumes:
    postgres_data:
