# Generated by Django 4.0.5 on 2022-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_pet_delete_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('CT', 'Cat'), ('DG', 'Dog')], default='DG', max_length=30),
        ),
    ]
