# Generated by Django 4.0.5 on 2022-06-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pet_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=20),
        ),
    ]
